name: Create Zip Archive

on: push

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create zip archive
        run: |
          zip -r extension.zip extension
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Create zip archive"
          add: "extension.zip"
