name: Create Zip Archive
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Zip Archive
        run: |
          zip -r extension.zip extension/
      - name: Upload Zip Archive
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: extension.zip
