name: Zip
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create zip
        run: cd ./extension && zip -r ../extension.zip ./
        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "extension.zip"
          tag: "Release"
