name: Create Zip Archive
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Zip Archive
        run: |
          zip -r extension.zip extension/
      - name: Add Zip Archive to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          directory: .
          force: true
          clean: false
          message: Add extension.zip to repository
