name: Zip
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create zip
        run: cd ./extension && zip -r ../extension.zip ./
        
      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: '["extension.zip"]'
          message: 'Create archive'
          push: true
