name: Zip
on:
  push:
    paths:
      - extension/**
      - .github/**
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set Manifest Version Number
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '1.1.1'
          replace: version${{ steps.tag_version.outputs.new_tag }}
          include: "**manifest.json"
          regex: false
          
      - uses: actions/upload-artifact@v3
        with:
          name: manifest.json
          path: ./extension
          
      - name: Set Manifest Version Number
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: 'versionv0'
          replace: "0"
          include: "**manifest.json"
          regex: false
          
      - uses: actions/upload-artifact@v3
        with:
          name: manifest.json
          path: ./extension
      
      - name: Create zip
        run: cd ./extension && zip -r ../chrome-based.zip ./
        
      - name: Fix Manifest
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '"service_worker": "service_worker.js"'
          replace: '"scripts": [ "service_worker.js" ]'
          include: "**manifest.json"
          regex: false
        
      - uses: actions/upload-artifact@v3
        with:
          name: manifest.json
          path: ./extension
        
      - name: Create zip
        run: cd ./extension && zip -1 -r ../firefox.xpi ./
        
      - uses: trmcnvn/firefox-addon@v1
        with:
          # uuid is only necessary when updating an existing addon,
          # omitting it will create a new addon
          uuid: '{de7bb9b678c44811a736}'
          xpi: firefox.xpi
          manifest: ./extension/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "chrome-based.zip, firefox.xpi"
