name: Zip
on:
  push:
    paths:
      - extension/**
      - .github/**
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create zip
        run: cd ./extension && zip -r ../chrome-based.zip ./
        
      - name: Fix Manifest
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '"service_worker": "service_worker.js"'
          replace: '"scripts": [ "service_worker.js" ]'
          include: 'manifest.json'
          regex: false
        
      - name: Create zip
        run: cd ./extension && zip -r ../firefox.zip ./  
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "chrome-based.zip, firefox.zip"
