name: Zip Repository
on:
  push:
    branches:
      - master

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - name: Zip-Release4cpp
      uses: darshitsri/zip-release@v3
      with:
        # Filename for archive
        filename: extension.zip
        # List of excluded files / directories
        exclusions: .github, .git, extension.zip
